services:
  g_hsl_cs:
    image: gbezirci/hslcomingsoon
    ports:
      - 2082:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker